export enum EstadoProducto {
    DISPONIBLE = 'DISPONIBLE',
    NO_DISPONIBLE = 'NO_DISPONIBLE',
    DISPONIBLE_DEFECTUOSO = 'DISPONIBLE_DEFECTUOSO'
  }
  
  export enum TipoProducto {
    ELABORADO_A_MANO = 'ELABORADO_A_MANO',
    ELABORADO_A_MANO_Y_MAQUINA = 'ELABORADO_A_MANO_Y_MAQUINA'
  }
  